version: "3.8"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
